### ISSUE TITLE
Commit on antlr/jetbrains broke sample

### ISSUE THREAD

**Issue by MichaelSnowden** [antlr/jetbrains-plugin-sample#4]
This commit https://github.com/antlr/jetbrains/commit/57db94ac49ddb5eeb674b6e9b71d936037223f94

Broke (at least) this source file: /jetbrains-plugin-sample/src/java/org/antlr/jetbrains/sample/psi/VardefSubtree.java.

The constructor signature was changed.

It's very easy to get around this:

```
$ cd adaptor
$ git checkout 0f4e20755f8ae7fe5bec1e8f52ccefab42f33a87
```

But I think this repo should still be fixed because it took me a while to figure out.

**Comment by yegorpetrov** [comment]
I think a proper fix would be to edit [`FunctionSubtree`](https://github.com/antlr/jetbrains-plugin-sample/blob/7c400e02f89477dbe179123a2d43f839b4df05d7/src/java/org/antlr/jetbrains/sample/psi/VardefSubtree.java#L9) and [`VardefSubtree`](https://github.com/antlr/jetbrains-plugin-sample/blob/7c400e02f89477dbe179123a2d43f839b4df05d7/src/java/org/antlr/jetbrains/sample/psi/FunctionSubtree.java#L18) from `{ super(node); }` to `{ super(node, SampleParserDefinition.ID); }`.

**Comment by kshchepanovskyi** [comment]
Fixed here: https://github.com/kshchepanovskyi/jetbrains-plugin-sample/blob/gradle-integration/src/main/java/org/antlr/jetbrains/sample/psi/VardefSubtree.java

(PR is not merged yet)

**Comment by parrt** [comment]
thanks guys!

**Comment by bjansen** [comment]
This was fixed in https://github.com/antlr/jetbrains-plugin-sample/commit/0323b9123ba6428a57f1908d77b810741d12b033, thanks for reporting the problem!
