### ISSUE TITLE
NoClassDefFoundError

### ISSUE THREAD

**Issue by AbnerZheng** [antlr/jetbrains-plugin-sample#6]
Hi, I tried run this project, and the compile phase seams to be well, but when running the program,  this error appear:
```
[   8276]  ERROR - i.util.KeyedExtensionCollector - org/antlr/v4/runtime/Parser 
java.lang.NoClassDefFoundError: org/antlr/v4/runtime/Parser
```
I have set the path variable as the antlr official website says:
``` 
export CLASSPATH=".:/usr/local/lib/antlr-4.5.3-complete.jar    :$CLASSPATH"
```
Could anyone help me solving the problem?

**Comment by parrt** [comment]
Building a plugin is complicated; your question indicates you might not be ready for that ;) You need to add antlr to your intellij build path. isn't there a pom.xml or something there?
