### ISSUE TITLE
Lexer causes offset mismatch -> IllegalStateException; no file displayed

### ISSUE THREAD

**Issue by azrdev** [antlr/jetbrains-plugin-sample#9]
I'm trying to use [my Prolog grammar](https://github.com/antlr/grammars-v4/blob/master/prolog/prolog.g4) to build a jetbrains prolog plugin. I appended a rule `ERRCHAR: . ->channel(HIDDEN);` and rewrote/threw out all the "sample language" specific stuff, so I can run the IDE with my plugin. Opening a prolog file doesn't work, however, I see in idea.log this backtrace (repeatedly, with different origins):

~~~
2018-03-07 22:36:34,339 [ 451765]  ERROR - oncurrency.BoundedTaskExecutor - Unexpected termination offset for lexer org.antlr.jetbrains.adaptor.lexer.ANTLRLexerAdaptor@5dc85b57 
java.lang.IllegalStateException: Unexpected termination offset for lexer org.antlr.jetbrains.adaptor.lexer.ANTLRLexerAdaptor@5dc85b57
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.doSetText(LexerEditorHighlighter.java:394)
	at com.intellij.openapi.editor.ex.util.LexerEditorHighlighter.setText(LexerEditorHighlighter.java:360)
	at com.intellij.openapi.fileEditor.impl.text.AsyncHighlighterUpdater.performInReadAction(AsyncHighlighterUpdater.java:59)
	at com.intellij.openapi.progress.util.ReadTask.lambda$runBackgroundProcess$0(ReadTask.java:66)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:47)
	at com.intellij.openapi.progress.util.ReadTask.runBackgroundProcess(ReadTask.java:66)
~~~

Debugging shows me that the exception stems here https://github.com/JetBrains/intellij-community/blob/master/platform/editor-ui-ex/src/com/intellij/openapi/editor/ex/util/LexerEditorHighlighter.java#L394
because `textLength` (by the ANTLR lexer) is one bigger than `mySegments.myEnds[last]`.

Has anybody else encountered a similar error? Is it a fault in my rewrite of the surrounding plugin files, or a bug somewhere else?
Would anybody be willing to look into the problem, if I publish the project so far?

**Comment by Shan1024** [comment]
@azrdev - Have you used any modes in the grammar?

**Comment by azrdev** [comment]
@Shan1024 no (but maybe I will have to later)

**Comment by Shan1024** [comment]
@azrdev - I encountered this issue but could not find any solution for it yet. I thought it was due to some issue in modes since it occurs in one mode that I have. Seems like that is not the case then.

**Comment by bjansen** [comment]
Right, this is described in the [SDK docs](https://www.jetbrains.org/intellij/sdk/docs/reference_guide/custom_language_support/implementing_lexer.html?search=lexer):

> **Note:** Lexers, and in particular JFlex-based lexers, need to be created in such a way that they always match the entire contents of the file, without any gaps between tokens, and generate special tokens for characters which are not valid at their location. Lexers must never abort prematurely because of an invalid character.

For ANTLRv4 grammars, this means that you should **never** `skip()` tokens, but rather use `channel(HIDDEN)` instead like @nixel2007 suggested.

See also https://github.com/antlr/antlr4-intellij-adaptor/issues/3 and [this explanation from someone working at JetBrains](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360003023860--Custom-Language-Plugin-Highlighter-doesn-t-update-colors-sometimes-no-errors-in-log-?page=1#community_comment_360000354619).
